### ISSUE TITLE
Bwok bwok, cluck bwak bwak bwak

### ISSUE THREAD

**Issue by kalatabe** [sebastiancarlos/chicken-ipsum#3]

**Comment by kalatabe** [comment]
Chicken chicken chicken—chicken chicken chicken chicken chi-
cken, chicken chicken chicken chicken chicken chicken chicken
chicken chicken C(log n) [2]. Chicken p. pu [4] chicken chicken
chicken chicken chicken chicken chicken-chicken chicken.

**Comment by sebastiancarlos** [comment]
Bok cluck-a-buh-gawk Cock-a-doodle-doo! 🙏
